# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [16.x, 17.x]
    steps:
      - name: Build for ${{ matrix.node-version }}
        uses: ./.github/workflows/build.yml
        with:
          node-version: ${{ matrix.node-version }}
